{"uuid": "93705584-571b-4ce7-9e46-c69015aeecb9", "children": ["3696c32a-bdcf-4a6a-a7b1-86a34d5eaa89"], "befores": [{"name": "xunit_setup_class_fixture_TestPjj", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.liinji.liinjias.test' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'E:\\\\Android\\\\SDK\\\\platform-tools\\\\adb.exe -P 5037 -s b8b46013 shell am start -W -n com.liinji.liinjias.test/activity.LoginNewActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 255'; Stderr: 'Exception occurred while executing 'start':\r\njava.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.liinji.liinjias.test/activity.LoginNewActivity } from null (pid=29064, uid=2000) not exported from uid 10501\r\n\tat com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1107)\r\n\tat com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1103)\r\n\tat com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:749)\r\n\tat com.android.server.wm.ActivityTaskManagerService.startActivityAndWait(ActivityTaskManagerService.java:1390)\r\n\tat com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:3756)\r\n\tat com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:548)\r\n\tat com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:185)\r\n\tat android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)\r\n\tat android.os.ShellCommand.exec(ShellCommand.java:44)\r\n\tat com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10887)\r\n\tat android.os.Binder.shellCommand(Binder.java:932)\r\n\tat android.os.Binder.onTransact(Binder.java:816)\r\n\tat android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5274)\r\n\tat com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2948)\r\n\tat android.os.Binder.execTransactInternal(Binder.java:1162)\r\n\tat android.os.Binder.execTransact(Binder.java:1126)'; Code: '255'\n\n", "trace": "  File \"d:\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\workspaces\\SeleniumPython\\Script\\test_pjj.py\", line 20, in setup_class\n    self.driver = GetDriver.init_driver()\n  File \"E:\\workspaces\\SeleniumPython\\Basic\\Get_Driver.py\", line 27, in init_driver\n    cls.driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_caps)\n  File \"d:\\python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 157, in __init__\n    AppiumConnection(command_executor, keep_alive=keep_alive), desired_capabilities, browser_profile, proxy\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\python37\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 226, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1635992416223, "stop": 1635992423180}], "start": 1635992416223, "stop": 1635992423295}